title: The New Dynamic
baseURL: https://www.thenewdynamic.com
DefaultContentLanguage: en
enableRobotsTXT: true

markup:
  highlight:
    style: monokai
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

social:
  twitter: theNewDynamic
outputs:
  home:
    - HTML
    - tnd_redirects_netlify
    - tnd_headers_netlify

privacy:
  youtube:
    privacyEnhanced: true
  twitter:
    enableDNT: true
